from enum import Enum


class TamanhosDeTelas(Enum):

    TELA_27P_1920_X_1080 = 1
    TELA_156P_1366_768 = 2   
    

class PosicoesSecaoDependentes(Enum):
    BOTAO_NOVO = 1
    BOTAO_OK_CADASTRAR = 2

class PosicoesSecaoBensEDireitos(Enum):
    BOTAO_NOVO = 1
    BOTAO_OK_CADASTRAR = 2

class SecoesDoSistema(Enum):
    SECAO_IDENTIFICACAO_DO_CONTRIBUINTE = 1
    SECAO_SAIDA_DEFINITIVA = 2
    SECAO_ESPOLIO = 3
    SECAO_DEPENDENTES = 4
    SECAO_ALIMENTANDOS = 5
    SECAO_HERDEIROS_MEIEIROS = 6
    SECAO_RENDIMENTOS_TRIBUTAVEIS_RECEBIDOS_DE_PJ = 7
    SECAO_RENDIMENTOS_RECEBIDOS_DE_PF_OU_EXTERIOR = 8
    SECAO_RENDIMENTOS_ISENTOS_E_NAO_TRIBUTAVEIS = 9
    SECAO_RENDIMENTOS_SUJEITOS_A_TRIBUTACAO_EXCLUSIVA_DEFINITIVA = 10
    SECAO_RENDIMENTOS_TRIBUTAVEIS_DE_PJ_SUSPENSA = 11
    SECAO_RENDIMENTOS_RECEBIDOS_ACUMULATIVAMENTE = 12
    SECAO_IMPOSTO_RETIDO_PAGO = 13
    SECAO_PAGAMENTOS_EFETUADOS = 14
    SECAO_DOACOES_EFETUADAS = 15
    SECAO_DOACOES_DIRETAMENTE_NA_DECLARACAO = 16
    SECAO_BENS_E_DIREITOS = 17
    SECAO_DIVIDAS_E_ONUS_REAIS = 18
    SECAO_DOACOES_A_PARTIDOS_POLITICOS_E_CANDIDATOS = 19
    
    
class NovaDeclaracao(Enum):
    BOTAO_NOVA_DECLARACAO = 1
    OPCAO_DECLARACAO_DE_AJUSTE_ANUAL = 2
    OPCAO_DECLARACAO_FINAL_DE_ESPOLIO = 3
    OPCAO_DECLARACAO_DE_SAIDA_DEFINITIVA = 4
    BOTAO_INICIAR_DECLARACAO_EM_BRANCO = 5
    CAIXA_INSERCAO_DO_CPF = 6
    CAIXA_INSERCAO_DO_NOME = 7
    BOTAO_OK_DECLARACAO_EM_BRANCO = 8
    BOTAO_OK_CONFIRMACAO = 9